blank_issues_enabled: false
contact_links:
  - name: 💬 Diskussion · Discussion
    url: https://github.com/thecodingdad/quadro-3D/discussions
    about: "Fragen, Ideen, allgemeines Feedback · Questions, ideas, general feedback"
